#!/bin/sh
#

switched_dirs="false"
if gitroot=$(git rev-parse --show-toplevel); then
	echo found a git root at $gitroot, running from there...
	pushd $gitroot || cd $gitroot
	switched_dirs="true"
else
	echo this is not a git repo, assuming root is \$PWD
fi

OUT=$PWD/doc/generated
export QT_INSTALL_DOCS

if [ -z "$QT_INSTALL_DOCS" ]; then
	if [ -d /usr/share/doc/qt5/global/macros.qdocconf ]; then
		QT_INSTALL_DOCS=/usr/share/doc/qt5
	elif [ -d /usr/share/qt5/doc/global/macros.qdocconf ]; then
		QT_INSTALL_DOCS=/usr/share/doc/qt5
	fi
fi

# this is searched relative to the qdocconf file!!
export SAILFISH_INSTALL_DOCS=sailfish-qdoc-template/config

[ -d $OUT ] && rm -r $OUT

qdoc --no-examples --outputdir $OUT --outputformat HTML --installdir $QMAKE_INSTALL_ROOT/doc doc/qdoc/master.qdocconf --single-exec  $@

[ $switched_dirs = "true" ] && popd || cd -
