# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       patchmanager

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    patchmanager allows you to manage Sailfish OS patches
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    TODO
URL:        http://github.com/SfietKonstantin/patchmanager
Source0:    %{name}-%{version}.tar.bz2
Source100:  patchmanager.yaml
Requires:   ausmt
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10

%description
patchmanager allows managing system patch
on your SailfishOS device easily. This package
contains the system daemon.


%package ui
Summary:    GUI for patchmanager
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}

%description ui
patchmanager allows managing system patch
on your SailfishOS device easily. This package
contains the GUI.


%package patches
Summary:    A set of patches for patchmanager
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}

%description patches
patchmanager allows managing system patch
on your SailfishOS device easily. This package
contains a set of patches.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%preun
# >> preun
dbus-send --system --type=method_call \
--dest=org.SfietKonstantin.patchmanager /org/SfietKonstantin/patchmanager \
org.SfietKonstantin.patchmanager.quit
# << preun

%post
# >> post
dbus-send --system --type=method_call \
--dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
# << post

%postun
# >> postun
dbus-send --system --type=method_call \
--dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
# << postun

%files
%defattr(-,root,root,-)
%{_sbindir}/%{name}
%{_datadir}/%{name}/tools
%{_datadir}/dbus-1/
%{_sysconfdir}/dbus-1/system.d/
# >> files
# << files

%files ui
%defattr(-,root,root,-)
%{_bindir}/%{name}-ui
%{_datadir}/%{name}/qml
%{_datadir}/%{name}/data
%{_datadir}/applications/
%{_datadir}/icons/
# >> files ui
# << files ui

%files patches
%defattr(-,root,root,-)
%{_datadir}/%{name}/patches
# >> files patches
# << files patches
