#!/bin/sh
set -euCf
export POSIXLY_CORRECT=1
export LC_ALL=POSIX  # For details see https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_02

PM_CONF=/etc/patchmanager2.conf
PM_EXE=/usr/sbin/patchmanager

function usage() {
  printf "Patchmanager tool is a front-end for the patchmanager executable.\n"
  printf "USAGE: %s [-a|-A|-d|-D|-e|-h] [-f <filepath>]\n" $0
  printf "\t-a | --activate\t\t\tActivate / apply Patches from list or file (via -f).\n"
  printf "\t-A | --activate-all\t\tActivate / apply all Patches formerly marked as active.\n"
  printf "\t-d | --deactivate\t\tDeactivate / unapply Patches from list or file (via -f).\n"
  printf "\t-D | --deactivate-all\t\tDeactivate / unapply all Patches.\n"
  printf "\t-f | --file <filepath>\t\tUse <filepath> for the list of Patches.\n"
  printf "\t-e | --export\t\t\tExport list of Patches marked as active either to STDout or (via -f) to a file.\n"
  printf "\t-h | --help\t\t\tPrint this help.\n"
  printf "* The list must be comprised of (internal) names of patches, separated by white-spaces, commas or both.\n"
  printf "* For writing to <filepath>, it must not already exist and must be in a writable directory.\n"
  printf "* For reading from <filepath>, it must be a plain text file containing the (internal) names of patches, separated by white-spaces, commas or both.\n"
  printf "* The -a, -A, -d, -D options must be executed as root to be effective, otherwise they output a script with the commands to execute.\n"
  printf "* In order to use this tool as a drop-in replacement for calling the patchmanager executable, its options -u (synonym to -d), --unapply-all (synonym to -D) and --reset-system are also supported.\n"
  printf "Exit codes:\n"
  printf "\t0: All went fine.\n"
  printf "\t1: Incorrect parameter(s) provided.\n"
  printf "\t2: Error when interacting with the filesystem.\n"
  printf "\t3: Malformed Patch name provided.\n"
}

patchlist=""
operation=""
case "$1" in
  -a|--activate)
    operation="-a"
    shift
    if [ "$1" = "-f" ] || [ "$1" = "--file" ]; then
      shift
      filepath="$1"
      shift
      if [ -n "$*" ]; then
        printf 'Too many parameters: %s\n' "$*"
        exit 1
      else
        if [ -r "$filepath" ] && [ -s "$filepath" ]; then
          patchlist="$(tr ',[:blank:]' ' ' < "$filepath" | tr -s ' ')"
        else
          printf 'File %s does not exist, is empty or not readable.\n' "$filepath"
          exit 2
        fi
      fi
    else
      patchlist="$(printf '%s' "$*" | tr ',[:blank:]' ' ' | tr -s ' ')"
    fi
  ;;
  -A|--activate-all)
    operation="-a"
    shift
    if [ -n "$*" ]; then
      printf 'Too many parameters: %s\n' "$*"
    else
      if [ -r $PM_CONF ] && [ -s $PM_CONF ] && [ -f $PM_CONF ]; then
        patchlist="$(grep '^applied=' $PM_CONF | cut -s -d "=" -f 2- | tr ',[:blank:]' ' ' | tr -s ' ')"
      else
        printf 'File %s does not exist, is empty, not readable or not a regular file.\n' $PM_CONF
        exit 2
      fi
    fi
  ;;
  -d|-u|--deactivate)
    operation="-u"
    shift
    if [ "$1" = "-f" ] || [ "$1" = "--file" ]; then
      shift
      filepath="$1"
      shift
      if [ -n "$*" ]; then
        printf 'Too many parameters: %s\n' "$*"
        exit 1
      else
        if [ -r "$filepath" ] && [ -s "$filepath" ]; then
          patchlist="$(tr ',[:blank:]' ' ' < "$filepath" | tr -s ' ')"
        else
          printf 'File %s does not exist, is empty or not readable.\n' "$filepath"
          exit 2
        fi
      fi
    else
      patchlist="$(printf '%s' "$*" | tr ',[:blank:]' ' ' | tr -s ' ')"
    fi
  ;;
  -D|--deactivate-all|--unapply-all)
    operation="--unapply-all"
    shift
    if [ -n "$*" ]; then
      printf 'Too many parameters: %s\n' "$*"
      exit 1
    fi
  ;;
  --reset-system)
    operation="--reset-system"
    shift
    if [ -n "$*" ]; then
      printf 'Too many parameters: %s\n' "$*"
      exit 1
    fi
  ;;
  -e|--export)
    shift
    if [ "$1" = "-f" ] || [ "$1" = "--file" ]; then
      shift
      filepath="$1"
      shift
      if [ -n "$*" ]; then
        printf 'Too many parameters: %s\n' "$*"
        exit 1
      else
        if [ ! -w $(dirname "$filepath") ]; then
          printf "Cannot write to given directory: %s\n" "$filepath" >&2
          exit 2
        elif [ -e "$filepath" ]; then
          printf "File %s exists, will not overwrite.\n" "$filepath" >&2
          exit 2
        else
          grep '^applied=' $PM_CONF | cut -s -d "=" -f 2- > "$filepath"
          exit 0
        fi
      fi
    elif [ -n "$*" ]; then
      printf 'Too many parameters: %s\n' "$*"
      exit 1
    else
      printf '%s\n' "$(grep '^applied=' $PM_CONF | cut -s -d "=" -f 2-)"
      exit 0
    fi
  ;;
  -h|--help)
    usage
    exit 0
  ;;
  *)
    usage
    exit 1
  ;;
esac

uid=$(id -u)
if [ ! $uid -eq 0 ]; then
  printf "Not running as root, hence only listing the commands to execute.\nYou can redirect this into a file and execute it as root.\n\n" >&2
  printf "#!/bin/sh\n\n"
fi
for p in $patchlist; do
  if printf '%s' "$p" | grep -q '^[[:alnum:]_.+-]'; then
    printf 'Illegal character in Patch name: %s' "$p"
    exit 3
  elif [ $uid -eq 0 ]; then
    $PM_EXE $operation $p
    sleep 0.2
  else
    printf "%s %s %s; sleep 0.2\n" $PM_EXE $operation $p
  fi
done
