#!/bin/bash
set -o pipefail
#
# Some constants
#

# Root
PM_VAR_DIR="/tmp/patchmanager3"
PATCH_ROOT_DIR="/usr/share/patchmanager/patches"

# Paths / Files
PATCH_DIR="$PATCH_ROOT_DIR/$1"

PM_LOG_FILE="$PM_VAR_DIR/patchmanager.log"
PM_PATCH_BACKUP_ROOT_DIR="$PM_VAR_DIR/patches"
PM_PATCH_BACKUP_DIR="$PM_PATCH_BACKUP_ROOT_DIR/$1"

SYS_BITNESS=$(/usr/bin/getconf LONG_BIT)

# Constants
PATCH_NAME="unified_diff.patch"
PATCH_PATH="$PATCH_DIR/$PATCH_NAME"
PATCH_EDITED_NAME="unified_diff_${SYS_BITNESS}bit.patch"

# list of candidate paths to attempt 32/64bit library path correction
MANGLE_CANDIDATES=""
if [ -r "etc/patchmanager/manglelist.conf" ] ; then
    source /etc/patchmanager/manglelist.conf
fi

ROOT_DIR="/tmp/patchmanager"

# Applications
PATCH_EXEC="/usr/bin/patch"

#
# Here starts the part where all the magic happens
#

#
# Helper functions that do all the needed heavy work
#

log() {
  echo "$@" | tee -a "$PM_LOG_FILE"
}

failure() {
  log
  log "*** FAILED ***"
  log

  exit 1
}

success() {
  log
  log "*** SUCCESS ***"
  log

  exit 0
}

test_if_applied() {
  if [ -f "$PATCH_PATH" ]; then
    log
    log "----------------------------------"
    log "Test if already applied patch"
    log "----------------------------------"
    log

    $PATCH_EXEC -R -p 1 -d "$ROOT_DIR" --dry-run < "$PATCH_PATH" 2>&1 | tee -a "$PM_LOG_FILE"

    if [ $? -eq 0 ]; then
      success
    fi
  fi
}

# see issue #71: https://github.com/sailfishos-patches/patchmanager/issues/71
mangle_libpath() {
    if [ -f "$PATCH_PATH" ]; then
      log
      log "----------------------------------"
      [ $SYS_BITNESS -eq 32 ] && log "Checking paths for 32->64bit conversion"
      [ $SYS_BITNESS -eq 64 ] && log "Checking paths for 64->32bit conversion"
      log "----------------------------------"
      log

      found=0
      candidates="$MANGLE_CANDIDATES"
      if [ $SYS_BITNESS -eq 32 ]; then
        # first, convert the candidate list
        # variable expansion ${foo/lib/lib64} would work on bash, but not POSIX/ash/busybox
        candidates=$(printf '%s' "$MANGLE_CANDIDATES" | sed 's@/usr/lib/@/usr/lib64/@g' )
      fi

      for p in $candidates; do
        totl_lines=$(grep -c "^+++" "$PATCH_PATH")
        cand_lines=$(grep -c "^+++ $p" "$PATCH_PATH")
        if [ $cand_lines -eq 0 ]; then
          continue # nothing found, try next
        else
          found=$(( $found + $cand_lines ))
          if [ $totl_lines -ne $cand_lines ]; then
            # if there are several references in the patch file our mangling might do too much and cause the patch to fail.
            log "WARNING: mixed patch, conversion might not work"
          fi
        fi

        patch_edited_path="$PM_PATCH_BACKUP_DIR"/"$PATCH_EDITED_NAME"
        log "found: ${p}, replacing libpath references"

        mkdir -p "$PM_PATCH_BACKUP_DIR"
        # prepare the pattern
        pr=""
        if [ $SYS_BITNESS -eq 32 ]; then
          pr=$(printf '%s' "$p" | sed 's@/usr/lib64/@/usr/lib/@')
        elif [ $SYS_BITNESS -eq 64 ]; then
          pr=$(printf '%s' "$p" | sed 's@/usr/lib/@/usr/lib64/@')
        fi
        # doit
        printf '#\n# patch converted to %sbit library paths from original by Patchmanager 3.1\n# Date: %s\n#\n' $SYS_BITNESS $(date -Iseconds) > "$patch_edited_path"
        sed "s@^+++ $p@+++ $pr@;s@^--- $p@--- $pr@" "$PATCH_PATH" >> "$patch_edited_path"
        if [ $? -ne 0 ]; then
          failure
        fi
        log
        log "----------------------------------"
        log "Conversion produced: $patch_edited_path"
        log "----------------------------------"
        log
        # set the patch to apply to the new one:
        PATCH_PATH="$patch_edited_path"
        return
      done
      if [ $found -eq 0 ]; then
        log
        log "----------------------------------"
        log "Found nothing to convert, OK"
        log "----------------------------------"
        log
       fi
    fi
}

verify_text_patch() {
  if [ -f "$PATCH_PATH" ]; then
    log
    log "----------------------------------"
    log "Dry running patch"
    log "----------------------------------"
    log

    $PATCH_EXEC -p 1 -d "$ROOT_DIR" --dry-run < "$PATCH_PATH" 2>&1 | tee -a "$PM_LOG_FILE"

    if [ $? -ne 0 ]; then
      failure
    fi
  fi
}

install_text_patch() {
  if [ -f "$PATCH_PATH" ]; then
    log
    log "----------------------------------"
    log "Applying text patch"
    log "----------------------------------"
    log

    $PATCH_EXEC -p 1 -d "$ROOT_DIR" --no-backup-if-mismatch < "$PATCH_PATH" 2>&1 | tee -a "$PM_LOG_FILE"
  fi
}

create_backup_patch() {
  log
  log "----------------------------------"
  log "Creating backup patch"
  log "----------------------------------"
  log

  mkdir -p "$PM_PATCH_BACKUP_DIR" > /dev/null 2>&1
  cp -f "$PATCH_DIR/$PATCH_NAME" "$PM_PATCH_BACKUP_DIR" > /dev/null 2>&1
  log "Created backup"
  log "  backup: $PM_PATCH_BACKUP_DIR"
}

#
# Bunch of safety checks and required initializations
#

mkdir -p "$PM_VAR_DIR" > /dev/null 2>&1

if [ ! -f "$PM_LOG_FILE" ]; then
  log "*** Patch Log Created by Apply $(date) ***"
fi

log
log "----------------------------------"
log "PM APPLY $(date)"
log "----------------------------------"
log

log "$(basename "$PATCH_DIR")"

if [ -f "$PATCH_PATH" ]; then
  log "  contains text patch"
fi

log

if [ ! -x "$PATCH_EXEC" ]; then
  log "ERROR: Cannot find $PATCH_EXEC"
  failure
fi

if [ -z "$PATCH_DIR" ]; then
  log "ERROR: PATCH_DIR must be given for installing"
  failure
fi

if [ ! -d "$PATCH_DIR" ]; then
  log "ERROR: $PATCH_DIR is not a directory or does not exist!"
  failure
fi

if [ ! -f "$PATCH_PATH" ]; then
  log "ERROR: Cannot find patch file !"
  failure
fi

#
# The main function that controls all the magic stuff
#

test_if_applied

mangle_libpath

verify_text_patch

install_text_patch

create_backup_patch

success

exit 0
